version: "3.9"

# DB vols
volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:

  #Standalone Chrome selenium on port 4444
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: SiteSelenium
    ports:
        - "4444:4444"

    networks:
       djangonetwork:
          ipv4_address: 192.168.0.111
    privileged: true
    shm_size: 2g
    environment:
          - SE_NODE_MAX_SESSIONS=20
          - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  #nginx serve Web continer at port 8001
  nginx:
    image: nginx:alpine
    container_name: SiteNgnix
    ports:
      - "8001:8001"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork

  #Hold python Code
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: SiteWeb
    depends_on:
      - db
      - selenium
    volumes:
      - ./src:/src
    expose:
      - "8001"

    env_file:
      - ./.envs/.django
    networks:
       djangonetwork:
          ipv4_address: 192.168.0.110

  #postgresql DB
  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: SiteDb
    env_file:
      - ./.envs/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork


#docker net bridge
networks:
  djangonetwork:
    driver: bridge
    ipam:
        driver: default
        config:
              - subnet: 192.168.0.0/24
